---
title: "F1"
author: "Erica"
date: "1/19/2021"
output: html_document
---

# Criterium 1
```{r cmmi}

library(rvest)
library(pander)
library(xml2)
library(tidyverse)
```

### Web scraping and data cleaning
```{r }


# Scrape whole item-card data from all pages; separate into 500 pages at the time so code runs faster
itemcard_1_500 <- lapply(paste0('https://cmmiinstitute.com/pars/?StateId=33296d0d-c5c5-4d47-b36b-c692d73a5ab7&PageNumber=', 1:500),
                function(url){
                  url %>% read_html() %>% 
                    html_nodes("div.item-card") %>% 
                    html_text()
                })

itemcard_501_1000 <- lapply(paste0('https://cmmiinstitute.com/pars/?StateId=33296d0d-c5c5-4d47-b36b-c692d73a5ab7&PageNumber=', 501:1000),
                function(url){
                  url %>% read_html() %>% 
                    html_nodes("div.item-card") %>% 
                    html_text()
                })

itemcard_1001_1500 <- lapply(paste0('https://cmmiinstitute.com/pars/?StateId=33296d0d-c5c5-4d47-b36b-c692d73a5ab7&PageNumber=', 1001:1500),
                function(url){
                  url %>% read_html() %>% 
                    html_nodes("div.item-card") %>% 
                    html_text()
                })

itemcard_1500_1913 <- lapply(paste0('https://cmmiinstitute.com/pars/?StateId=33296d0d-c5c5-4d47-b36b-c692d73a5ab7&PageNumber=', 1501:1913),
                function(url){
                  url %>% read_html() %>% 
                    html_nodes("div.item-card") %>% 
                    html_text()
                })

# turn lists into dfs
df_1_500 <- as.data.frame(do.call(rbind, lapply(itemcard_1_500, as.data.frame)))
df_501_1000 <- as.data.frame(do.call(rbind, lapply(itemcard_501_1000, as.data.frame)))
df_1001_1500 <- as.data.frame(do.call(rbind, lapply(itemcard_1001_1500, as.data.frame)))
df_1501_1913 <- as.data.frame(do.call(rbind, lapply(itemcard_1500_1913, as.data.frame)))
df_1_1913

df_ml3 <- as.data.frame(do.call(rbind, lapply(itemcard_ML3_USA, as.data.frame)))
df_ml4 <- as.data.frame(do.call(rbind, lapply(itemcard_ML4_USA, as.data.frame)))
df_ml5 <- as.data.frame(do.call(rbind, lapply(itemcard_ML5_USA, as.data.frame)))
df_ml3_4_3 <- rbind(df_ml3, df_ml4, df_ml5)

# bind dfs consecutively
df_1_1000 <- rbind(df_1_500, df_501_1000)
df_1_1500 <- rbind(df_1_1000, df_1001_1500)
df_1_1913 <- rbind(df_1_1500, df_1501_1913)

# remove unnecesary dfs after done
rm(df_1_500)
rm(df_501_1000)
rm(df_1001_1500)
rm(df_1501_1913)
rm(df_1_1000)
rm(df_1_1500)

# work with df_1_1913

df <- df_1_1913

# remove repeating "[\r\n]" character
orgs1 <- trimws(gsub("[\r\n]", "", df$`X[[i]]`))
df$`X[[i]]` <- orgs1
colnames(df) <- "x"

# separate organization/company name from the rest of the text per row entry
df1 <- df %>% separate(
  col = x,
  into = c("org", "id_level"),
  sep = ":",
  remove = TRUE,
  convert = FALSE,
  extra = "warn",
  fill = "warn"
)

```


### Assign SAM status, CMMI level, and other data cleaning. Search for "with SAM" or "without SAM" from the company entry and create a new column that designates the "SAM status" of the company. Repeat for ML2-5 to designate "CMMI level"
```{r}

# separate out SAM, levels, etc.
# df1$sam_status <- ifelse(grepl("with SAM",df1$id_level),'with SAM', ifelse(grepl("without SAM", df1$id_level), 'without SAM', 'something_else'))

df1$level_status <- ifelse(grepl("ML2",df1$id_level),'ML2',
                           ifelse(grepl("ML3",df1$id_level),'ML3',
                                  ifelse(grepl("ML4",df1$id_level),'ML4',
                                         ifelse(grepl("ML5",df1$id_level),'ML5', 'something_else'))))

# remove out "ID" from org name
df2 <- df1 %>% separate(
  col = org,
  into = c("org", "null"),
  sep = "ID",
  remove = TRUE,
  convert = FALSE,
  extra = "warn",
  fill = "warn"
)

df2$null <- NULL

# add CMMI-SVC or -DEV; may not be needed
# df2$cmmi_type <- ifelse(grepl("CMMI-SVC",df2$id_level),'CMMI-SVC', ifelse(grepl("CMMI-DEV", df2$id_level), 'CMMI-DEV', 'something_else'))

#df2 <- df2[-1369,] # weird company, no relevant data

# fix ids to add; not necessary right now
df2$id <- trimws(df2$id)
id_extracted <- str_extract_all(df2$id, "0.|1.|2.|3.|4.|5.|6.|7.|8.|9.")
id_str <- trimws(id$id)
df2$id_ex <- id_ex
id_ex_v2 <- trimws(gsub("#first term ends in space, . , or - ", "", df2$id_ex))


# create a new df with company name, sam status, cmmi level, and cmmi type

```


### Select  companies with >= ML3 and with SAM
```{r}

cmmi <- df2

# select SAM with >= ML3
cmmi_ml3 <- cmmi %>% filter(grepl("ML3", cmmi$level_status))
cmmi_ml4 <- cmmi %>% filter(grepl("ML4", cmmi$level_status))
cmmi_ml5 <- cmmi %>% filter(grepl("ML5", cmmi$level_status))

cmmi_final <- rbind(cmmi_ml3, cmmi_ml4, cmmi_ml5)

cmmi_final_select <- cmmi_final %>%
  dplyr::select(org, level_status)

# export to Excel
library(writexl)
write_xlsx(cmmi_final, "cmmi_2021_ML3_ML4_ML5_world.xlsx")
```



```{r}
# Regular expression to standardize company names from CMMI website; just a few more additions to "to_remove" as above.

cmmi <- cmmi_final_select


to_remove_cmmi <- c("\\ LLC$",
               "\\, LLC$", 
               "\\. Inc.$\\", 
               "\\. Inc.$", 
               "\\ INC$", 
               "\\Inc$", 
               "\\Co.$", 
               "\\INC.$", 
               "\\, INC$",
               "\\, INC.$",
               "\\, Inc$",
               "\\, Inc.$",
               "\\L.L.C.$", 
               "\\, L.L.C.$",
               "\\Corp.$", 
               "\\Ltd.$",
               "\\LLC.$",
               "\\L.LC.$",
               "\\, L.LC$",
               "\\L.C.$",
               "\\Llc$",
               "\\PLLC$",
               "\\inc$",
               "\\, Ltd.$",
               "\\, Llc$",
               "\\, PLLC$",
               "\\#1$",
               "\\Co$",
               "\\Corp$",
               "\\CORPORATION$",
               "\\Incorporated$",
               "\\LLP$",
               "\\CORP.$",
               "\\, L L C$",
               "\\CORP$",
               "\\, inc$",
               "\\LLLP$",
               "\\(INC)$",
               "\\, L.L.L.P$",
               "\\ LP$",
               "\\ PC$",
               "\\ P.C$",
               "\\LTD$",
               "\\, LTD$",
               "\\Pvt Ltd",
               "\\Pvt.",
               "\\Private Limited*",
               "\\Pvt.$",
               "\\, LTD",
               "\\, Ltd",
               "\\Limited$",
               "\\,*",
               "\\.*",
               "CO.,LTD.$",
               "COLTD$",
               "LIMITED LIABILITY COMPANY$"
               )

# Standardize company names; use toupper() to convert character strings to uppercase

cmmi$a <- gsub("\\s+$", "", as.character(cmmi$org)) # removes multiple spaces from the end of the string
cmmi$a <- toupper(gsub("\\s*\\([^\\)]+\\)", "", as.character(cmmi$a)))
cmmi$b <- gsub(toupper(paste(to_remove_cmmi,collapse="|")),"",as.character(cmmi$a))
cmmi$c <- toupper(gsub(paste(to_remove_cmmi,collapse="|"),"",as.character(cmmi$b)))
cmmi$c <- toupper(gsub(paste(to_remove_cmmi,collapse="|"),"",as.character(cmmi$c)))
cmmi$d <- gsub("\\TECHNOLOGIES*|\\TECHNOLOGY*","TECH",as.character(cmmi$c))
cmmi$d <- gsub("\\COMPANIES|\\COMPANY","CO",as.character(cmmi$d))
cmmi$d <- toupper(gsub("\\BAE SYSTEMS ELECTRONIC SYSTEMS","BAE SYSTEMS INFORMATION AND ELECTRONIC SYSTEMS INTEGRATION ",as.character(cmmi$d))) # a specific modification to a company name
cmmi$d <- gsub("\\s+$", "", as.character(cmmi$d)) # removes multiple spaces from the end of the string

cmmi_standarized <- cmmi %>%
  dplyr::select(org, level_status, d)

write_xlsx(cmmi_standarized, "CMMI.xlsx")

```

```{r}
# compare cmmi_final vs. cmmi_standarized

# Aerojet Rocketdyne Holdings, Inc
# X Technologies, Inc

anti_cmmi_sam <- sam_select %>%
  dplyr::anti_join(cmmi_standarized, by="d", suffix = c("_sam","_cmmi"))

```


# SAM
```{r}
library(readxl)
sam <- read_excel("company-unique-list.xlsx")

# select
sam_select <- sam %>%
  dplyr::select(Name, DUNS, Country) %>%
  dplyr::filter(Country=="UNITED STATES")

# regex
to_remove_cmmi <- c("\\ LLC$",
               "\\, LLC$", 
               "\\. Inc.$\\", 
               "\\. Inc.$", 
               "\\ INC$", 
               "\\Inc$", 
               "\\Co.$", 
               "\\INC.$", 
               "\\, INC$",
               "\\, INC.$",
               "\\, Inc$",
               "\\, Inc.$",
               "\\L.L.C.$", 
               "\\, L.L.C.$",
               "\\Corp.$", 
               "\\Ltd.$",
               "\\LLC.$",
               "\\L.LC.$",
               "\\, L.LC$",
               "\\L.C.$",
               "\\Llc$",
               "\\PLLC$",
               "\\inc$",
               "\\, Ltd.$",
               "\\, Llc$",
               "\\, PLLC$",
               "\\#1$",
               "\\Co$",
               "\\Corp$",
               "\\CORPORATION$",
               "\\Incorporated$",
               "\\LLP$",
               "\\CORP.$",
               "\\, L L C$",
               "\\CORP$",
               "\\, inc$",
               "\\LLLP$",
               "\\(INC)$",
               "\\, L.L.L.P$",
               "\\ LP$",
               "\\ PC$",
               "\\ P.C$",
               "\\LTD$",
               "\\, LTD$",
               "\\Pvt Ltd",
               "\\Pvt.",
               "\\Private Limited*",
               "\\Pvt.$",
               "\\, LTD",
               "\\, Ltd",
               "\\Limited$",
               "\\,*",
               "\\.*",
               "CO.,LTD.$",
               "COLTD$",
               "LIMITED LIABILITY COMPANY$"
               )

sam_select$a <- gsub("\\s+$", "", as.character(sam_select$Name)) # removes multiple spaces from the end of the string
sam_select$a <- toupper(gsub("\\s*\\([^\\)]+\\)", "", as.character(sam_select$a)))
sam_select$b <- gsub(toupper(paste(to_remove_cmmi,collapse="|")),"",as.character(sam_select$a))
sam_select$c <- toupper(gsub(paste(to_remove_cmmi,collapse="|"),"",as.character(sam_select$b)))
sam_select$c <- toupper(gsub(paste(to_remove_cmmi,collapse="|"),"",as.character(sam_select$c)))
sam_select$d <- gsub("\\TECHNOLOGIES*|\\TECHNOLOGY*","TECH",as.character(sam_select$c))
sam_select$d <- gsub("\\COMPANIES|\\COMPANY","CO",as.character(sam_select$d))
sam_select$d <- toupper(gsub("\\BAE SYSTEMS ELECTRONIC SYSTEMS","BAE SYSTEMS INFORMATION AND ELECTRONIC SYSTEMS INTEGRATION ",as.character(sam_select$d))) # a specific modification to a company name
sam_select$d <- gsub("\\s+$", "", as.character(sam_select$d)) # removes multiple spaces from the end of the string

sam_regex <- sam_select %>%
  dplyr::select(Name, DUNS, d, Country)

cmmi_sam <- sam_regex %>%
  dplyr::inner_join(cmmi_standarized, by="d", suffix = c("_sam","_cmmi")) %>%
  dplyr::select(Name, DUNS, Country, d, org, level_status)

cmmi_sam <- cmmi_sam[!duplicated(cmmi_sam$DUNS),]

colnames(cmmi_sam) <- c("name_sam","recipient_duns","country","name_regex","name_cmmi","CMMI")

cmmi_sam$recipient_duns <- as.character(cmmi_sam$recipient_duns )

write_xlsx(cmmi_sam, "SAM_CMMI.xlsx")
```







# Award
```{r}
# Read csv file with awards data from FY21
library(readr)
library(writexl)
library(dplyr)

# FY20
url_awards_fy20 <- "https://files.usaspending.gov/award_data_archive/FY2020_All_Contracts_Full_20210109.zip"
download.file(url_awards_fy20, "awards_fy20.zip")
unzip("awards_fy20.zip")

# 1
fy20_1 <- read_csv("FY2020_All_Contracts_Full_20210111_1.csv") 
fy20_1 <- fy20_1 %>%
  dplyr::select(recipient_name, award_description, recipient_duns, naics_code, naics_description, cage_code, recipient_parent_name, recipient_parent_duns, recipient_country_name)
fy20_1_duns <- fy20_1[!duplicated(fy20_1$recipient_duns),]

# 2
fy20_2 <- read_csv("FY2020_All_Contracts_Full_20210111_2.csv")
fy20_2 <- fy20_2 %>%
  dplyr::select(recipient_name, award_description, recipient_duns, naics_code, naics_description, cage_code, recipient_parent_name, recipient_parent_duns, recipient_country_name)
fy20_2_duns <- fy20_2[!duplicated(fy20_2$recipient_duns),]

# 3
fy20_3 <- read_csv("FY2020_All_Contracts_Full_20210111_3.csv")
fy20_3 <- fy20_3 %>%
  dplyr::select(recipient_name, award_description, recipient_duns, naics_code, naics_description, cage_code, recipient_parent_name, recipient_parent_duns, recipient_country_name)
fy20_3_duns <- fy20_3[!duplicated(fy20_3$recipient_duns),]

# 4
fy20_4 <- read_csv("FY2020_All_Contracts_Full_20210111_4.csv")
fy20_4 <- fy20_4 %>%
  dplyr::select(recipient_name, award_description, recipient_duns, naics_code, naics_description, cage_code, recipient_parent_name, recipient_parent_duns, recipient_country_name)
fy20_4_duns <- fy20_4[!duplicated(fy20_4$recipient_duns),]

# 5
fy20_5 <- read_csv("FY2020_All_Contracts_Full_20210111_5.csv")
fy20_5 <- fy20_5 %>%
  dplyr::select(recipient_name, award_description, recipient_duns, naics_code, naics_description, cage_code, recipient_parent_name, recipient_parent_duns, recipient_country_name)
fy20_5_duns <- fy20_5[!duplicated(fy20_5$recipient_duns),]

# 6
fy20_6 <- read_csv("FY2020_All_Contracts_Full_20210111_6.csv")
fy20_6 <- fy20_6 %>%
  dplyr::select(recipient_name, award_description, recipient_duns, naics_code, naics_description, cage_code, recipient_parent_name, recipient_parent_duns, recipient_country_name)
fy20_6_duns <- fy20_6[!duplicated(fy20_6$recipient_duns),]

# 7 
fy20_7 <- read_csv("FY2020_All_Contracts_Full_20210111_7.csv")
fy20_7 <- fy20_7 %>%
  dplyr::select(recipient_name, award_description, recipient_duns, naics_code, naics_description, cage_code, recipient_parent_name, recipient_parent_duns, recipient_country_name)
fy20_7_duns <- fy20_7[!duplicated(fy20_7$recipient_duns),]

```



# Awards and CMMI
```{r}
fy20_1 <- fy20_1 %>%
  tibble() %>%
  dplyr::inner_join(cmmi_sam, by="recipient_duns", suffix=c("_award","cmmi")) %>%
  dplyr::select(recipient_name, recipient_duns, country, CMMI, naics_code, naics_description, cage_code, award_description)

fy20_2 <- fy20_2 %>%
  tibble() %>%
  dplyr::inner_join(cmmi_sam, by="recipient_duns", suffix=c("_award","cmmi")) %>%
  dplyr::select(recipient_name, recipient_duns, country, CMMI, naics_code, naics_description, cage_code, award_description)

fy20_3 <- fy20_3 %>%
  tibble() %>%
  dplyr::inner_join(cmmi_sam, by="recipient_duns", suffix=c("_award","cmmi")) %>%
  dplyr::select(recipient_name, recipient_duns, country, CMMI, naics_code, naics_description, cage_code, award_description)

fy20_4 <- fy20_4 %>%
  tibble() %>%
  dplyr::inner_join(cmmi_sam, by="recipient_duns", suffix=c("_award","cmmi")) %>%
  dplyr::select(recipient_name, recipient_duns, country, CMMI, naics_code, naics_description, cage_code, award_description)

fy20_5 <- fy20_5 %>%
  tibble() %>%
  dplyr::inner_join(cmmi_sam, by="recipient_duns", suffix=c("_award","cmmi")) %>%
  dplyr::select(recipient_name, recipient_duns, country, CMMI, naics_code, naics_description, cage_code, award_description)

fy20_6 <- fy20_6 %>%
  tibble() %>%
  dplyr::inner_join(cmmi_sam, by="recipient_duns", suffix=c("_award","cmmi")) %>%
  dplyr::select(recipient_name, recipient_duns, country, CMMI, naics_code, naics_description, cage_code, award_description)

fy20_7 <- fy20_7 %>%
  tibble() %>%
  dplyr::inner_join(cmmi_sam, by="recipient_duns", suffix=c("_award","cmmi")) %>%
  dplyr::select(recipient_name, recipient_duns, country, CMMI, naics_code, naics_description, cage_code, award_description)

FY20 <- rbind(fy20_1,fy20_2,fy20_3,fy20_4,fy20_5,fy20_6,fy20_7)
write_xlsx(FY20, "FY20.xlsx")

FY20_duns <- rbind(fy20_1_duns,fy20_2_duns,fy20_3_duns,fy20_4_duns,fy20_5_duns,fy20_6_duns,fy20_7_duns)

rm(fy20_1)
rm(fy20_2)
rm(fy20_3)
rm(fy20_4)
rm(fy20_5)
rm(fy20_6)
rm(fy20_7)

rm(fy20_1_duns)
rm(fy20_2_duns)
rm(fy20_3_duns)
rm(fy20_4_duns)
rm(fy20_5_duns)
rm(fy20_6_duns)
rm(fy20_7_duns)

```




# Crit 4
```{r}
# The algorithm should be to search (in contract descriptions) for contracts with at least one of the following 5 patterns: (1) "Oracle Financial", (2) "Oracle Financials", (3) "UFMS", (4)"Oracle Federal", or (5) "Unified Financial Management"

FY20$award_description <- toupper(FY20$award_description)

FY20$C4 <- ifelse(grepl("UFMS",FY20$award_description),'C4_met',
                                  ifelse(grepl("ORACLE FINANCIAL", FY20$award_description), 'C4_met', 
                                         ifelse(grepl("ORACLE FINANCIALS", FY20$award_description), 'C4_met', 
                                                ifelse(grepl("ORACLE FEDERAL", FY20$award_description), 'C4_met', 'something_else'))))

FY20_C4 <- FY20 %>%
    dplyr::filter(grepl("C4_met", FY20$C4))

FY20_C4_3 <- FY20_C4 %>%
   dplyr::count(recipient_duns) %>%
  dplyr::filter(n >= 3) %>%
  dplyr::inner_join(FY20_C4, by="recipient_duns")

FY20_C4_3 <- FY20_C4_3[!duplicated(FY20_C4_3$recipient_duns),] %>%
    dplyr::select(recipient_name, recipient_duns, country, CMMI)
```



# Crit 5
```{r}
# The algorithm should be to search (in contract descriptions) for contracts which both contains ONE of the words "cloud" or "AWS" or "Amazon Web", or "Azure", AND ALSO WHICH CONTAINS ONE on of the words "migrat" (with anything following it) or "trans" (with anything following it) or "deploy" (with anything following it). (Note the spelling of "migrat" and "trans" -- we want to catch various like migrate, migrating, migration, transformation, transmigration, etc.)

FY20$cloud <- ifelse(grepl("CLOUD",FY20$award_description),'cloud',
                                  ifelse(grepl("AWS", FY20$award_description), 'cloud', 
                                         ifelse(grepl("AMAZON WEB", FY20$award_description), 'cloud', 
                                                ifelse(grepl("AZURE", FY20$award_description), 'cloud', 'something_else'))))

FY20_cloud <- FY20 %>%
  dplyr::filter(grepl("cloud", FY20$cloud))

FY20_cloud$C5 <- ifelse(grepl("MIGRAT",FY20_cloud$award_description),'C5_met',
                                  ifelse(grepl("TRANS", FY20_cloud$award_description), 'C5_met', 
                                         ifelse(grepl("DEPLOY", FY20_cloud$award_description), 'C5_met', 'something_else')))

FY20_C5 <- FY20_cloud %>%
    dplyr::filter(grepl("C5_met", FY20_cloud$C5))

FY20_C5_2 <- FY20_C5 %>%
   dplyr::count(recipient_duns) %>%
  dplyr::filter(n >= 2) %>%
  dplyr::inner_join(FY20_C5, by="recipient_duns")

FY20_C5_2 <- FY20_C5_2[!duplicated(FY20_C5_2$recipient_duns),] %>%
  dplyr::select(recipient_name, recipient_duns, country, CMMI)
```



# F1
```{r}
F1_FY20 <- FY20_C5_2 %>%
  dplyr::inner_join(FY20_C4_3, by="recipient_duns", suffix = c("_c5","_c4"))
  
F1_FY20 <- rbind(FY20_C5_2, FY20_C4_3)

write_xlsx(F1_FY20, "factor1_FY2020.xlsx")
```





